Fix buildout version
Downgrade buildout to 1.7
Fix Build fails at bootstrap due to:

The constraint, 2.2.1, is not consistent with the requirement,
'zc.buildout<2dev'.
While:
  Bootstrapping.
  Error: Bad constraint 2.2.1 zc.buildout<2dev